import "./globals.css";

import type { Metadata } from "next";
import { Anton, Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";

import Footer from "@/components/common/footer";
import Header from "@/components/common/header";
import { NuqsProvider } from "@/providers/nuqs-provider";
import ReactQueryProvider from "@/providers/react-query";

import { getAllCategories } from "./data/categories/get-all-categories";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const anton = Anton({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anton",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await getAllCategories({
    withProducts: false,
    withVariants: false,
  });

  return (
    <html lang="pt">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${anton.variable} antialiased flex flex-col min-h-screen`}
      >
        <ReactQueryProvider>
          <NuqsProvider>
            <Header categories={categories} />
            <div className="flex-1">
              {children}
              <Toaster />
            </div>
            <Footer />
          </NuqsProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
